CREATE TABLE `CLIENTE` (
	`ID_CLIENTE` varchar(14) NOT NULL,
	`NOME` varchar(255) NOT NULL,
	`EMAIL` varchar(255) NOT NULL,
	`TEL` varchar(11) NOT NULL,
	PRIMARY KEY (`ID_CLIENTE`)
);

CREATE TABLE `SERVICO` (
	`ID_SERVICO` int NOT NULL AUTO_INCREMENT,
	`ID_CLIENTE` varchar(14) NOT NULL AUTO_INCREMENT,
	`DESCRICAO` varchar(255) NOT NULL,
	`TIPO` varchar(255) NOT NULL,
	`VALOR` double(12,2) NOT NULL DEFAULT '0',
	`TEMPO_ENTREGA` double(15) NOT NULL,
	`ALTURA` double(5,3) NOT NULL,
	`LARGURA` double(5,3) NOT NULL,
	`COMPRIMENTO` double(5,3) NOT NULL,
	PRIMARY KEY (`ID_SERVICO`)
);

ALTER TABLE `SERVICO` ADD CONSTRAINT `SERVICO_fk0` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `Cliente`(`ID_CLIENTE`);


